# Generated by Django 2.1.7 on 2019-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.CharField(max_length=200)),
                ('image_type', models.CharField(max_length=200)),
                ('image_size', models.CharField(max_length=200)),
            ],
        ),
    ]
