# Generated by Django 2.1.7 on 2019-04-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixels', models.IntegerField()),
                ('processing_time', models.FloatField()),
            ],
        ),
    ]
