# Generated by Django 2.1.7 on 2019-03-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
