# Generated by Django 2.1.7 on 2019-03-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0004_auto_20190323_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
