# Generated by Django 2.1.7 on 2019-03-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0005_auto_20190323_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(error_messages={'required': 'Please upload an image!'}, upload_to=''),
        ),
    ]
